### ISSUE TITLE
Add support for link snippet cards

### ISSUE THREAD

**Issue by gdaniel** [xatkit-bot-platform/botium-connector-xatkit#3]
These cards are printed with the action `ReactPlatform.ReplyLinkSnippet`.
See the associated [react component](https://github.com/xatkit-bot-platform/xatkit-chat-widget/blob/master/src/components/Widget/components/Conversation/components/Messages/components/SnippetWithImg/index.js) to know about the content of the received object.

**Comment by hamzaed** [comment]
The concept "card" exists in Botium. However, as far as I understood from the documentation (it's not really clear), there are no assertions for cards yet. [Quote](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/38502401/Howto+develop+your+own+Botium+connector#The-outgoing-message): 

> buttons, media, nlp, cards fields are similar. You can extract them if the Chatbot Provider supports them. (And you can check them with corresponding asserter (cards has no asserter yet!))

As a work around, I implemented this using `MEDIA` for images and a patterned text for titles and the links (title > link). See the example below:

```
ReactPlatform.ReplyLinkSnippet("title example", "http://example.com", "https://via.placeholder.com/150")
```

Test spec:

```
#bot
MEDIA https://via.placeholder.com/150
title example > http://example.com
```
